/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post99, git sha1 a1bb0255d) */

(* \amaranth.hierarchy  = "cfu" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module cfu(cmd_ready, cmd_payload_function_id, cmd_payload_inputs_0, cmd_payload_inputs_1, rsp_valid, rsp_ready, rsp_payload_outputs_0, reset, port0_addr, port1_addr, port2_addr, port3_addr, port0_din, port1_din, port2_din, port3_din, clk, rst, cmd_valid);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$1 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$10 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$11 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$13 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$14 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$15 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$17 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$18 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$19 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$2 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$21 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$22 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$23 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$25 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$26 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$27 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$29 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$3 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$4 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$5 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:250" *)
  wire [31:0] \$signal$6 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:251" *)
  wire \$signal$7 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:252" *)
  reg \$signal$9 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:184" *)
  input [9:0] cmd_payload_function_id;
  wire [9:0] cmd_payload_function_id;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:186" *)
  input [31:0] cmd_payload_inputs_0;
  wire [31:0] cmd_payload_inputs_0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:187" *)
  input [31:0] cmd_payload_inputs_1;
  wire [31:0] cmd_payload_inputs_1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:183" *)
  output cmd_ready;
  reg cmd_ready;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:182" *)
  input cmd_valid;
  wire cmd_valid;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:246" *)
  reg current_function_done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:245" *)
  reg [2:0] current_function_id;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback1_done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback1_in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback1_in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback1_output;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback2_done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback2_in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback2_in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback2_output;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback3_done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback3_in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback3_in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback3_output;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback4_done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback4_in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback4_in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback4_output;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback5_done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback5_in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback5_in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback5_output;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback6_done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback6_in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback6_in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback6_output;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fallback7_done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fallback7_in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fallback7_in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fallback7_output;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  wire fn0_done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  wire [31:0] fn0_in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  wire [31:0] fn0_in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  wire [31:0] fn0_output;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire fn0_start;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
  reg [1:0] fsm_state = 2'h0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:238" *)
  wire [2:0] funct3;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:239" *)
  wire [6:0] funct7;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$30 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$31 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$32 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$33 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$34 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$35 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$36 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:50" *)
  wire [6:0] \funct7$37 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port0_addr;
  wire [31:0] port0_addr;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port0_din;
  wire [31:0] port0_din;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port1_addr;
  wire [31:0] port1_addr;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port1_din;
  wire [31:0] port1_din;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port2_addr;
  wire [31:0] port2_addr;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port2_din;
  wire [31:0] port2_din;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:192" *)
  input [31:0] port3_addr;
  wire [31:0] port3_addr;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:193" *)
  input [31:0] port3_din;
  wire [31:0] port3_din;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:191" *)
  input reset;
  wire reset;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:190" *)
  output [31:0] rsp_payload_outputs_0;
  reg [31:0] rsp_payload_outputs_0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:189" *)
  input rsp_ready;
  wire rsp_ready;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:188" *)
  output rsp_valid;
  reg rsp_valid;
  (* src = "/home/nosferatu/Projects/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  output rst;
  wire rst;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire start;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$12 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$16 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$20 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$24 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$28 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  wire \start$8 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:244" *)
  reg [2:0] stored_function_id = 3'h0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:244" *)
  reg [2:0] \stored_function_id$next ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:247" *)
  reg [31:0] stored_output = 32'd0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:247" *)
  reg [31:0] \stored_output$next ;
  always @(posedge clk)
    stored_function_id <= \stored_function_id$next ;
  always @(posedge clk)
    fsm_state <= \fsm_state$next ;
  always @(posedge clk)
    stored_output <= \stored_output$next ;
  fallback1 fallback1 (
    .done(fallback1_done),
    .in0(fallback1_in0),
    .in1(fallback1_in1),
    .\output (fallback1_output)
  );
  fallback2 fallback2 (
    .done(fallback2_done),
    .in0(fallback2_in0),
    .in1(fallback2_in1),
    .\output (fallback2_output)
  );
  fallback3 fallback3 (
    .done(fallback3_done),
    .in0(fallback3_in0),
    .in1(fallback3_in1),
    .\output (fallback3_output)
  );
  fallback4 fallback4 (
    .done(fallback4_done),
    .in0(fallback4_in0),
    .in1(fallback4_in1),
    .\output (fallback4_output)
  );
  fallback5 fallback5 (
    .done(fallback5_done),
    .in0(fallback5_in0),
    .in1(fallback5_in1),
    .\output (fallback5_output)
  );
  fallback6 fallback6 (
    .done(fallback6_done),
    .in0(fallback6_in0),
    .in1(fallback6_in1),
    .\output (fallback6_output)
  );
  fallback7 fallback7 (
    .done(fallback7_done),
    .in0(fallback7_in0),
    .in1(fallback7_in1),
    .\output (fallback7_output)
  );
  fn0 fn0 (
    .clk(clk),
    .done(fn0_done),
    .in0(fn0_in0),
    .in1(fn0_in1),
    .\output (fn0_output),
    .rst(rst),
    .start(fn0_start)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    current_function_id = 3'h0;
    (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          current_function_id = funct3;
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          current_function_id = stored_function_id;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    current_function_done = 1'h0;
    (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* full_case = 32'd1 *)
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:277" *)
          casez (current_function_id)
            3'h0:
                current_function_done = \$signal$1 ;
            3'h1:
                current_function_done = \$signal$4 ;
            3'h2:
                current_function_done = \$signal$7 ;
            3'h3:
                current_function_done = \$signal$11 ;
            3'h4:
                current_function_done = \$signal$15 ;
            3'h5:
                current_function_done = \$signal$19 ;
            3'h6:
                current_function_done = \$signal$23 ;
            3'h?:
                current_function_done = \$signal$27 ;
          endcase
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:289" *)
          casez (current_function_id)
            3'h0:
                current_function_done = \$signal$1 ;
            3'h1:
                current_function_done = \$signal$4 ;
            3'h2:
                current_function_done = \$signal$7 ;
            3'h3:
                current_function_done = \$signal$11 ;
            3'h4:
                current_function_done = \$signal$15 ;
            3'h5:
                current_function_done = \$signal$19 ;
            3'h6:
                current_function_done = \$signal$23 ;
            3'h?:
                current_function_done = \$signal$27 ;
          endcase
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    cmd_ready = 1'h0;
    (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          cmd_ready = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \stored_function_id$next  = stored_function_id;
    (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          if (cmd_valid) begin
            \stored_function_id$next  = cmd_payload_function_id[2:0];
          end
    endcase
    (* src = "/home/nosferatu/Projects/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    if (rst) begin
      \stored_function_id$next  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$signal$2  = 1'h0;
    \$signal$5  = 1'h0;
    \$signal$9  = 1'h0;
    \$signal$13  = 1'h0;
    \$signal$17  = 1'h0;
    \$signal$21  = 1'h0;
    \$signal$25  = 1'h0;
    \$signal$29  = 1'h0;
    (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          if (cmd_valid) begin
            (* full_case = 32'd1 *)
            (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:282" *)
            casez (current_function_id)
              3'h0:
                  \$signal$2  = 1'h1;
              3'h1:
                  \$signal$5  = 1'h1;
              3'h2:
                  \$signal$9  = 1'h1;
              3'h3:
                  \$signal$13  = 1'h1;
              3'h4:
                  \$signal$17  = 1'h1;
              3'h5:
                  \$signal$21  = 1'h1;
              3'h6:
                  \$signal$25  = 1'h1;
              3'h?:
                  \$signal$29  = 1'h1;
            endcase
          end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    rsp_valid = 1'h0;
    (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          if (cmd_valid) begin
            (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
            if (current_function_done) begin
              rsp_valid = 1'h1;
            end
          end
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          if (current_function_done) begin
            rsp_valid = 1'h1;
          end
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          rsp_valid = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    rsp_payload_outputs_0 = 32'd0;
    (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          if (cmd_valid) begin
            (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
            if (current_function_done) begin
              (* full_case = 32'd1 *)
              (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:262" *)
              casez (current_function_id)
                3'h0:
                    rsp_payload_outputs_0 = \$signal ;
                3'h1:
                    rsp_payload_outputs_0 = \$signal$3 ;
                3'h2:
                    rsp_payload_outputs_0 = \$signal$6 ;
                3'h3:
                    rsp_payload_outputs_0 = \$signal$10 ;
                3'h4:
                    rsp_payload_outputs_0 = \$signal$14 ;
                3'h5:
                    rsp_payload_outputs_0 = \$signal$18 ;
                3'h6:
                    rsp_payload_outputs_0 = \$signal$22 ;
                3'h?:
                    rsp_payload_outputs_0 = \$signal$26 ;
              endcase
            end
          end
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          if (current_function_done) begin
            (* full_case = 32'd1 *)
            (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:262" *)
            casez (current_function_id)
              3'h0:
                  rsp_payload_outputs_0 = \$signal ;
              3'h1:
                  rsp_payload_outputs_0 = \$signal$3 ;
              3'h2:
                  rsp_payload_outputs_0 = \$signal$6 ;
              3'h3:
                  rsp_payload_outputs_0 = \$signal$10 ;
              3'h4:
                  rsp_payload_outputs_0 = \$signal$14 ;
              3'h5:
                  rsp_payload_outputs_0 = \$signal$18 ;
              3'h6:
                  rsp_payload_outputs_0 = \$signal$22 ;
              3'h?:
                  rsp_payload_outputs_0 = \$signal$26 ;
            endcase
          end
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          rsp_payload_outputs_0 = stored_output;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \fsm_state$next  = fsm_state;
    (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          if (cmd_valid) begin
            (* full_case = 32'd1 *)
            (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
            if (current_function_done) begin
              (* full_case = 32'd1 *)
              (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
              if (rsp_ready) begin
                \fsm_state$next  = 2'h0;
              end else begin
                \fsm_state$next  = 2'h1;
              end
            end else begin
              \fsm_state$next  = 2'h2;
            end
          end
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* full_case = 32'd1 *)
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          if (current_function_done) begin
            (* full_case = 32'd1 *)
            (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
            if (rsp_ready) begin
              \fsm_state$next  = 2'h0;
            end else begin
              \fsm_state$next  = 2'h1;
            end
          end else begin
            \fsm_state$next  = 2'h2;
          end
      /* \amaranth.decoding  = "WAIT_TRANSFER/1" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:291" */
      2'h1:
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:296" *)
          if (rsp_ready) begin
            \fsm_state$next  = 2'h0;
          end
    endcase
    (* src = "/home/nosferatu/Projects/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    if (rst) begin
      \fsm_state$next  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \stored_output$next  = stored_output;
    (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:272" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "WAIT_CMD/0" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:273" */
      2'h0:
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:279" *)
          if (cmd_valid) begin
            (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
            if (current_function_done) begin
              (* full_case = 32'd1 *)
              (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
              if (rsp_ready) begin
              end else begin
                (* full_case = 32'd1 *)
                (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:267" *)
                casez (current_function_id)
                  3'h0:
                      \stored_output$next  = \$signal ;
                  3'h1:
                      \stored_output$next  = \$signal$3 ;
                  3'h2:
                      \stored_output$next  = \$signal$6 ;
                  3'h3:
                      \stored_output$next  = \$signal$10 ;
                  3'h4:
                      \stored_output$next  = \$signal$14 ;
                  3'h5:
                      \stored_output$next  = \$signal$18 ;
                  3'h6:
                      \stored_output$next  = \$signal$22 ;
                  3'h?:
                      \stored_output$next  = \$signal$26 ;
                endcase
              end
            end
          end
      /* \amaranth.decoding  = "WAIT_INSTRUCTION/2" */
      /* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:284" */
      2'h2:
          (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:259" *)
          if (current_function_done) begin
            (* full_case = 32'd1 *)
            (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:263" *)
            if (rsp_ready) begin
            end else begin
              (* full_case = 32'd1 *)
              (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:267" *)
              casez (current_function_id)
                3'h0:
                    \stored_output$next  = \$signal ;
                3'h1:
                    \stored_output$next  = \$signal$3 ;
                3'h2:
                    \stored_output$next  = \$signal$6 ;
                3'h3:
                    \stored_output$next  = \$signal$10 ;
                3'h4:
                    \stored_output$next  = \$signal$14 ;
                3'h5:
                    \stored_output$next  = \$signal$18 ;
                3'h6:
                    \stored_output$next  = \$signal$22 ;
                3'h?:
                    \stored_output$next  = \$signal$26 ;
              endcase
            end
          end
    endcase
    (* src = "/home/nosferatu/Projects/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    if (rst) begin
      \stored_output$next  = 32'd0;
    end
  end
  assign rst = reset;
  assign \funct7$37  = funct7;
  assign fallback7_in1 = cmd_payload_inputs_1;
  assign fallback7_in0 = cmd_payload_inputs_0;
  assign \funct7$36  = funct7;
  assign fallback6_in1 = cmd_payload_inputs_1;
  assign fallback6_in0 = cmd_payload_inputs_0;
  assign \funct7$35  = funct7;
  assign fallback5_in1 = cmd_payload_inputs_1;
  assign fallback5_in0 = cmd_payload_inputs_0;
  assign \funct7$34  = funct7;
  assign fallback4_in1 = cmd_payload_inputs_1;
  assign fallback4_in0 = cmd_payload_inputs_0;
  assign \funct7$33  = funct7;
  assign fallback3_in1 = cmd_payload_inputs_1;
  assign fallback3_in0 = cmd_payload_inputs_0;
  assign \funct7$32  = funct7;
  assign fallback2_in1 = cmd_payload_inputs_1;
  assign fallback2_in0 = cmd_payload_inputs_0;
  assign \funct7$31  = funct7;
  assign fallback1_in1 = cmd_payload_inputs_1;
  assign fallback1_in0 = cmd_payload_inputs_0;
  assign \funct7$30  = funct7;
  assign fn0_in1 = cmd_payload_inputs_1;
  assign fn0_in0 = cmd_payload_inputs_0;
  assign \start$28  = \$signal$29 ;
  assign \$signal$27  = fallback7_done;
  assign \$signal$26  = fallback7_output;
  assign \start$24  = \$signal$25 ;
  assign \$signal$23  = fallback6_done;
  assign \$signal$22  = fallback6_output;
  assign \start$20  = \$signal$21 ;
  assign \$signal$19  = fallback5_done;
  assign \$signal$18  = fallback5_output;
  assign \start$16  = \$signal$17 ;
  assign \$signal$15  = fallback4_done;
  assign \$signal$14  = fallback4_output;
  assign \start$12  = \$signal$13 ;
  assign \$signal$11  = fallback3_done;
  assign \$signal$10  = fallback3_output;
  assign \start$8  = \$signal$9 ;
  assign \$signal$7  = fallback2_done;
  assign \$signal$6  = fallback2_output;
  assign start = \$signal$5 ;
  assign \$signal$4  = fallback1_done;
  assign \$signal$3  = fallback1_output;
  assign fn0_start = \$signal$2 ;
  assign \$signal$1  = fn0_done;
  assign \$signal  = fn0_output;
  assign funct7 = cmd_payload_function_id[9:3];
  assign funct3 = cmd_payload_function_id[2:0];
endmodule

(* \amaranth.hierarchy  = "cfu.fallback1" *)
(* generator = "Amaranth" *)
module fallback1(done, in0, in1, \output );
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "cfu.fallback2" *)
(* generator = "Amaranth" *)
module fallback2(done, in0, in1, \output );
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "cfu.fallback3" *)
(* generator = "Amaranth" *)
module fallback3(done, in0, in1, \output );
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "cfu.fallback4" *)
(* generator = "Amaranth" *)
module fallback4(done, in0, in1, \output );
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "cfu.fallback5" *)
(* generator = "Amaranth" *)
module fallback5(done, in0, in1, \output );
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "cfu.fallback6" *)
(* generator = "Amaranth" *)
module fallback6(done, in0, in1, \output );
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "cfu.fallback7" *)
(* generator = "Amaranth" *)
module fallback7(done, in0, in1, \output );
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  wire done;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  wire [31:0] \output ;
  assign in1s = in1;
  assign in0s = in0;
  assign done = 1'h1;
  assign \output  = in0;
endmodule

(* \amaranth.hierarchy  = "cfu.fn0" *)
(* generator = "Amaranth" *)
module fn0(done, start, in0, in1, rst, clk, \output );
  reg \$auto$verilog_backend.cc:2352:dump_module$2  = 0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/proj/anodecfu/cfu.py:8" *)
  wire [32:0] \$1 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/proj/anodecfu/cfu.py:8" *)
  wire [32:0] \$2 ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  output done;
  reg done = 1'h0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:53" *)
  reg \done$next ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:48" *)
  input [31:0] in0;
  wire [31:0] in0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:54" *)
  wire [31:0] in0s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:49" *)
  input [31:0] in1;
  wire [31:0] in1;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:55" *)
  wire [31:0] in1s;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  output [31:0] \output ;
  reg [31:0] \output  = 32'd0;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:51" *)
  reg [31:0] \output$next ;
  (* src = "/home/nosferatu/Projects/CFU-Playground/third_party/python/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/nosferatu/Projects/CFU-Playground/python/amaranth_cfu/cfu.py:52" *)
  input start;
  wire start;
  assign \$2  = in0 + (* src = "/home/nosferatu/Projects/CFU-Playground/proj/anodecfu/cfu.py:8" *) in1;
  always @(posedge clk)
    \output  <= \output$next ;
  always @(posedge clk)
    done <= \done$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    \output$next  = \output ;
    (* src = "/home/nosferatu/Projects/CFU-Playground/proj/anodecfu/cfu.py:7" *)
    if (start) begin
      \output$next  = \$2 [31:0];
    end
    (* src = "/home/nosferatu/Projects/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    if (rst) begin
      \output$next  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$2 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/nosferatu/Projects/CFU-Playground/proj/anodecfu/cfu.py:7" *)
    if (start) begin
      \done$next  = 1'h1;
    end else begin
      \done$next  = 1'h0;
    end
    (* src = "/home/nosferatu/Projects/CFU-Playground/third_party/python/amaranth/amaranth/hdl/xfrm.py:519" *)
    if (rst) begin
      \done$next  = 1'h0;
    end
  end
  assign \$1  = \$2 ;
  assign in1s = in1;
  assign in0s = in0;
endmodule
