export DEFINES :=

# skip debug code
DEFINES += NDEBUG

DEFINES += INCLUDE_MODEL_PDTI8
# DEFINES += INCLUDE_MODEL_MICRO_SPEECH
# DEFINES += INCLUDE_MODEL_MAGIC_WAND
# DEFINES += INCLUDE_MODEL_MNV2
# DEFINES += INCLUDE_MODEL_HPS
# DEFINES += INCLUDE_MODEL_MLCOMMONS_TINY_V01_ANOMD
# DEFINES += INCLUDE_MODEL_MLCOMMONS_TINY_V01_IMGC
# DEFINES += INCLUDE_MODEL_MLCOMMONS_TINY_V01_KWS
# DEFINES += INCLUDE_MODEL_MLCOMMONS_TINY_V01_VWW

# includes all the above models
# DEFINES += INCLUDE_ALL_TFLM_EXAMPLES

DEFINES += DONUT_DEMO

include ../proj.mk
